language: php

php:
  - 5.4 

env:
  - BOOST_INCLUDES="/home/kportal/usr/include/boost" BOOST_LIBS="/home/kportal/usr/lib" CPATH="/home/kportal/usr/include/" CPLUS_INCLUDE_PATH="/home/kportal/usr/include/"
before_install:
  - lsb_release -a
  - sudo apt-get update -qq 
  - sudo useradd -m kportal && pwd && ls -l && lsb_release -a && mkdir -p /home/travis/build/pyotr777/kportal/src/kdeskdaemon/obj && touch /home/travis/build/pyotr777/kportal/src/kdeskdaemon/obj/testfile
  - git submodule update --init --recursive  
install: sudo ./installkportal_ubuntu.sh
#script:
# - cd /home/travis/build/pyotr777/kportal/src && make && sudo make install

