language: cpp
sudo: required
services:
  - docker
install:
  - lsb_release -a
  - sudo apt-get update -qq 
  - sudo apt-get install socat
  - git submodule update --init --recursive  
script: 
  - travis_wait sudo ./installkportal_ubuntu.sh 
  - sudo su kportal -c 'whoami; echo $HOME'
  - sudo su kportal -c './src/release/start_apache.sh -travis'
  - sudo su kportal -c 'docker ps | grep apache'
  - sudo socat TCP4-LISTEN:9555,fork UNIX-CLIENT:/var/run/docker.sock &
  - sudo su kportal -c 'kp_server.sh 9004 -tls &'
  - sudo lsof -i -n -P | grep 80
  - sudo lsof -i -n -P | grep 9004
  - sudo lsof -i -n -P | grep 9005
#notifications:
#  slack: stair:XDlg9XLEBRkqAcuhSzQhu6vj

