language: cpp

services:
  - docker
install:
  - lsb_release -a
  - sudo apt-get update -qq 
  - git submodule update --init --recursive  
script: 
  - travis_wait sudo ./installkportal_ubuntu.sh 
  - sudo -u kportal docker ps | grep apache
  - sudo lsof -i -n -P | grep 80
  - sudo lsof -i -n -P | grep 9005
notifications:
  slack: stair:XDlg9XLEBRkqAcuhSzQhu6vj

