language: cpp
sudo: required
services:
  - docker
install:
  - lsb_release -a
  - sudo apt-get update -qq 
  - sudo apt-get install socat
  - git submodule update --init --recursive  
script: 
  - travis_wait 30 ./installkportal_ubuntu.sh 
  - sudo lsof -i -n -P | grep 80
  - sudo lsof -i -n -P | grep 9004
  - sudo lsof -i -n -P | grep 9005
notifications:
  slack: stair:XDlg9XLEBRkqAcuhSzQhu6vj

