language: cpp
sudo: required
services:
  - docker
install:
  - lsb_release -a
  - sudo apt-get update -qq 
  - git submodule update --init --recursive  
script: 
  - travis_wait sudo ./installkportal_ubuntu.sh 
  - echo "Test user kportal HOME"
  - sudo -E su kportal -c 'whoami; echo $HOME'
  - sudo su kportal -c 'whoami; echo $HOME'
  - sudo -u kportal -c 'whoami; echo $HOME'
  - sudo -u kportal ./src/release/start_apache.sh -travis 
  - sudo -u kportal kp_server.sh 9004 -tls
  - sudo -u kportal docker ps | grep apache
  - sudo lsof -i -n -P | grep 80
  - sudo lsof -i -n -P | grep 9004
  - sudo lsof -i -n -P | grep 9005
notifications:
  slack: stair:XDlg9XLEBRkqAcuhSzQhu6vj

