#!/bin/bash -e
# Copy installation files from current directory to remote machine
# and start remote installation.
# Require 1 parameter: remote [user@]hostname.

if [[ $# < 1 ]]; then
	echo "Usage:"
	echo "$(basename $0) [user@]hostname"
	echo "Requires working ssh connection to hostname."
	exit 0
fi

REMOTE=$1
REMOTEDIR="kportal/"
echo "Installing K-portal on $REMOTE in $REMOTEDIR."
echo "Detecting hostname and IP address."
EXT_IP=$(ssh $REMOTE "curl -m 5 ifconfig.me 2>/dev/null || curl -m 5 icanhazip.com 2>/dev/null" 2>/dev/null)
echo "IP detected: $EXT_IP"
REMOTE_HOSTNAME=$(ssh $REMOTE "dig +short -x $EXT_IP | sed 's/\.$//' 2>/dev/null" 2>/dev/null)
echo "Hostname detected: $REMOTE_HOSTNAME"


ssh $REMOTE hostname 2>/dev/null || (echo "Cannot connect with 'SSH $REMOTE'." && exit 1)

SSH_OPTIONS="-o ServerAliveInterval=15"

# Copy files to remote
echo "Synchronising installation files with remote location."
./sync_up.sh $REMOTE:$REMOTEDIR -do

echo "Starting remote installation web-server."

ssh $REMOTE $SSH_OPTIONS kportal/install_required_ubuntu.sh
# Kill webint server if its already running
ssh $REMOTE $SSH_OPTIONS "PID=\$(sudo lsof -i -n -P | grep '*:8080 (LISTEN)' | awk '{ print \$2 }' | head -1) && sudo kill \$PID" 2>/dev/null || true

./start_browser.sh $REMOTE_HOSTNAME:8080 &
echo "Start server"
ssh $REMOTE $SSH_OPTIONS -t kportal/start_webint_server.sh

