#!/bin/bash
# Script for local K-portal installation.
# Ubuntu OS required.

read -rd '' USAGE <<EOF
	Script for local K-portal installation.
	Usage:
	$(basename $0) [-d domain name]
	Domain name is part of URL of this K-portal installation as used in web browser.
	If no domain name parameter provided, domain name will be detected using "dig" command.
EOF

SOURCEDIR="kportal/"

# Trim quotes around a string
trimQuotes() {
	v=$1
	val=$(echo $v | sed 's/^\"//' | sed 's/\"$//')
	echo "$val"
}

while getopts "d:h" opt; do
	case $opt in
	d)
		DN=$(trimQuotes "$OPTARG")
		;;
	h)
		echo $USAGE
		exit 0
		;;	
	\?)
		echo "Invalid option: -$OPTARG" >&2
		echo "$USAGE"
		exit 1
		;;
	:)
		echo "Option -$OPTARG requires an argument." >&2
		echo -e "$USAGE"
		exit 1
		;;
	esac
done

set -e

if [[ -z "$DN" ]]; then
	echo "Detecting IP address."
	EXT_IP=$(curl -m 5 ifconfig.me 2>/dev/null || curl -m 5 icanhazip.com 2>/dev/null)
	echo "IP detected: $EXT_IP"
	echo "Detecting domain name."
	DN=$(dig +short -x $EXT_IP | sed 's/\.$//' 2>/dev/null)
	echo "Hostname detected: $DN"
fi

echo "DN=$DN"

echo "Starting local installation."
./install_required_ubuntu.sh
# Kill webint server if its already running
PID=$(sudo lsof -i -n -P | grep '*:8080 (LISTEN)' | awk '{ print $2 }' | head -1) && sudo kill $PID 2>/dev/null || true

./start_browser.sh $DN:8080 &
echo "Starting web interface server."
nohup ./start_webint_server.sh 2>/dev/null &
echo "Installation script will now quit."
echo "If your browser has not opened installation page already, open this page:"
echo -en "\033[38;5;27mhttp://$DN:8080\033[m\n"
