#!/bin/bash -e
# Copy installation files from current directory to remote machine
# and start remote installation.
# Require 1 parameter: remote [user@]hostname.

if [[ $# < 1 ]]; then
	echo "Usage:"
	echo "$(basename $0) [user@]hostname"
	echo "Requires working ssh connection to hostname."
	exit 0
fi

ssh $1 hostname 2>/dev/null
if [[ $? -ne 0 ]]; then
	echo "Cannot connect with ssh $1."
	exit 1
fi

SSH_OPTIONS="-o ServerAliveInterval=15"

# Copy files to remote
echo "Synchronising installation files with remote location."
./sync_up.sh $1 -do

echo "Starting remote installation web-server."


ssh $1 $SSH_OPTIONS kportal/start.sh

#echo "Starting remote installation web-server."
#ssh $1 'nohup $HOME/kportal/webint/webint.py </dev/null &'
#echo "Creating SSH tunnel"
#LOCAL_PORT=5000
#ssh -L $LOCAL_PORT:localhost:8080 $1 -f -N
#echo "Opening web address in browser."
#xdg-open &>/dev/null
#if [[ $? -ne 0 ]]; then
#	open http://localhost:$LOCAL_PORT
#else
#	xdg-open http://localhost:$LOCAL_PORT	
#fi
#
#if [[ $? -ne 0 ]]; then
#	echo "Open the following address in your Internet browser to continue installation:"
#	echo "http://localhost:$LOCAL_PORT"
#fi

