#!/bin/bash
# Start web inetrface (webint) server for K-portal setup.

read -rd '' USAGE <<EOF
    Script for starting web interface (webint) server for K-portal setup.
    Usage:
    $(basename $0) [user@]host [-i SSH identity file]
    Requires working SSH connection to host.
    If K-portal files are not on the host, run "install" script first.
EOF

if [[ $# < 1 ]]; then
    echo "$USAGE"
    exit 0
fi
while test $# -gt 0; do
    case "$1" in
        -h | --help)
            echo $USAGE
            exit 0
            ;;
        -i)
            KEY="-i $2";shift;
            ;;
        --) 
            shift
            break;;
        -*) 
            echo "Invalid option: $1"
            echo "$USAGE"
            exit 1;;
        *)
            REMOTE="$1"
            ;;
    esac
    shift
done

if [[ -z "$REMOTE" ]]; then
    echo "$USAGE"
    exit 1
fi

set -e

REMOTEDIR="kportal/"
echo "Starting web insterface server for K-portal setup."

SSH_COM="$KEY $REMOTE"

ssh $SSH_COM hostname &>/dev/null || (echo "Cannot connect with 'SSH $SSH_COM'." && exit 1)

SSH_OPTIONS="-o ServerAliveInterval=15"
ssh $SSH_COM $SSH_OPTIONS kportal/start_webint_server.sh



