global

	log 127.0.0.1   local0

	log 127.0.0.1   local1 notice

	maxconn 4096

	daemon

defaults

	log     global

	mode    http

	option  httplog

	option  dontlognull

	retries 3

	option redispatch

	option http-server-close

	maxconn 2000

	contimeout      5000

	clitimeout      50000

	srvtimeout      50000


backend www

	timeout server 30s

	server www1 127.0.0.1:9010

backend wss

	timeout server 600s

	server wss1 127.0.0.1:9004/kportal

frontend public

	bind *:9005 ssl crt /home/kportal/kportal_v1.1/src/www/AppMarket/ssl/server.crtkey

	acl is_websocket hdr(Upgrade) -i WebSocket

	acl is_websocket_server path_beg -i /kportal

	use_backend wss if is_websocket is_websocket_server

	default_backend www
