#!/bin/bash
if [[ $# < 2 ]]; then
    echo "Usage: $(basename $0) <instance id or tag Name> <Elastic IP address>"
    exit 1
fi

# Get ID by ID or tag
ID="$(awsls -s | grep $1 | awk '{ print $1 }')"
aws ec2 associate-address --instance-id $ID --public-ip $2 --allow-reassociation
